### ISSUE TITLE
Crash LC_SYMTAB

### ISSUE THREAD

**Issue by arasan01** [dmm-com/Ranasa#1]
## About

Failure in certain binaries

Problem
> stroff field plus strsize field of LC_SYMTAB command 1 extends past the end of the file

what is LC_TABSYM?
https://github.com/qyang-nj/llios/blob/main/macho_parser/docs/LC_SYMTAB.md

## what is the solution?

The Transmogrifier section is suspicious around the update, so fix it.

**Comment by fredikey** [comment]
@arasan01 Hi! Have you found any solution to this problem?

I have the same issue
<img width="1643" alt="image" src="https://github.com/dmm-com/Ranasa/assets/44212097/6c3612b9-9532-4456-a811-3a7a0e263632">

**Comment by arasan01** [comment]
@fredikey 
I do not have a solution to this problem. Also, since this tool will be a rather forced one, whether it works or not will strongly depend on the binary to which it is applied. The solution approach is to check the binary header and calculate if the LC_SYMTAB value is rewritten to the intended value.

**Comment by fredikey** [comment]
@arasan01 thanks for the reply! I'll try to fix it using your approach. if it works, I will send a PR

**Comment by arasan01** [comment]
@fredikey 
I know it's a lot of work, but good luck. I also recommend that you fork and use this repository as I am retired from dmm-com and have lost my privileges to this repository. Perhaps this repository is not properly maintained and thus the PR will be left alone.
